/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/assign`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/review`; params?: Router.UnknownInputParams; } | { pathname: `/scan`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Camera`; params?: Router.UnknownInputParams; } | { pathname: `/../services/backend`; params?: Router.UnknownInputParams; } | { pathname: `/pay`; params?: Router.UnknownInputParams; } | { pathname: `/../store/AppStore`; params?: Router.UnknownInputParams; } | { pathname: `/add-friend`; params?: Router.UnknownInputParams; } | { pathname: `/payment`; params?: Router.UnknownInputParams; } | { pathname: `/send`; params?: Router.UnknownInputParams; } | { pathname: `/receipt-details`; params?: Router.UnknownInputParams; } | { pathname: `/../services/backend.example`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/assign`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/review`; params?: Router.UnknownOutputParams; } | { pathname: `/scan`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Camera`; params?: Router.UnknownOutputParams; } | { pathname: `/../services/backend`; params?: Router.UnknownOutputParams; } | { pathname: `/pay`; params?: Router.UnknownOutputParams; } | { pathname: `/../store/AppStore`; params?: Router.UnknownOutputParams; } | { pathname: `/add-friend`; params?: Router.UnknownOutputParams; } | { pathname: `/payment`; params?: Router.UnknownOutputParams; } | { pathname: `/send`; params?: Router.UnknownOutputParams; } | { pathname: `/receipt-details`; params?: Router.UnknownOutputParams; } | { pathname: `/../services/backend.example`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/assign${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/review${`?${string}` | `#${string}` | ''}` | `/scan${`?${string}` | `#${string}` | ''}` | `/../components/Camera${`?${string}` | `#${string}` | ''}` | `/../services/backend${`?${string}` | `#${string}` | ''}` | `/pay${`?${string}` | `#${string}` | ''}` | `/../store/AppStore${`?${string}` | `#${string}` | ''}` | `/add-friend${`?${string}` | `#${string}` | ''}` | `/payment${`?${string}` | `#${string}` | ''}` | `/send${`?${string}` | `#${string}` | ''}` | `/receipt-details${`?${string}` | `#${string}` | ''}` | `/../services/backend.example${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/assign`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/review`; params?: Router.UnknownInputParams; } | { pathname: `/scan`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Camera`; params?: Router.UnknownInputParams; } | { pathname: `/../services/backend`; params?: Router.UnknownInputParams; } | { pathname: `/pay`; params?: Router.UnknownInputParams; } | { pathname: `/../store/AppStore`; params?: Router.UnknownInputParams; } | { pathname: `/add-friend`; params?: Router.UnknownInputParams; } | { pathname: `/payment`; params?: Router.UnknownInputParams; } | { pathname: `/send`; params?: Router.UnknownInputParams; } | { pathname: `/receipt-details`; params?: Router.UnknownInputParams; } | { pathname: `/../services/backend.example`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
